### PR TITLE
update preprint.bib

### PR DESCRIPTION
**Pull request by bboscoe**
swapped out wikipedia homoiconicity ref with Kay thesis

### CODE REVIEW

**Comment by danielskatz** [comment]
can you also update the .tex file to use this new reference, and the README.md so that it matches?

**Comment by bboscoe** [comment]
Ok so i made the changes to .tex file and readme as well, not sure how to add to this pull request or make another one?

**Comment by danielskatz** [comment]
the website says you should "Add more commits by pushing to the patch-1 branch on brandles/software-vs-data"

**Comment by danielskatz** [comment]
ok, I was able to go to your branch and make a PR, then I merged it, so I'm going to close this now

**Pull request closed without merging**
