### PR TITLE
Master

### PR DESCRIPTION
**Pull request by rwwh**
I suggest to add a statement about source and binary forms of compiled software.

### CODE REVIEW

**Comment by danielskatz** [comment]
Can you add any evidence/citations for this claim?

**Comment by rwwh** [comment]
Which claim would you need evidence for? Would  https://en.wikipedia.org/wiki/Compiler help?

I notice I added a backup file to the pull request.... the wonders of self-thinking GUIs....

**Comment by danielskatz** [comment]
I was hoping for a citation for "The existence of both source and compiled code must be taken into account in the license, this makes data collection licenses unsuitable for software and software licenses unsuitable for data collections" and another for "Furthermore subtle differences between different compilers (e.g. on two different machines or two different operating systems) can result in subtly different results when the software is run on the same data. This puts strong demands on the description of provenance."

**Comment by danielskatz** [comment]
I understand your point, but I'm not convinced it fits the document as a difference between software and data. Without some evidence (citation), I'm going to close this.

Also, it's now in conflict with the current document due to another recent change.

If you think I'm missing the point and you can provide evidence for your argument, please start a new PR.

Thanks.

**Pull request closed without merging**
